export const cadillac_models = [
  {
    id: 1,
    year: 2011,
    brand: "Cadillac",
    model: "CTS-V Coupe",
    topspeed: 308,
    power: 415,
    acceleration: 4.0,
    weight: 1783,
    cylinder: 8,
    torgue: 747,
    img: "2011_Cadillac_CTS-V_Coupe.jpg",
  },
  {
    id: 2,
    year: 2012,
    brand: "Cadillac",
    model: "Escalade ESV",
    topspeed: 170,
    power: 301,
    acceleration: 6.7,
    weight: 2713,
    cylinder: 8,
    torgue: 564,
    img: "2012_Cadillac_Escalade_ESV.jpg",
  },
];
