export const gumpert_models = [
  {
    id: 1,
    year: 2009,
    brand: "Gumpert",
    model: "Apollo S",
    topspeed: 330,
    power: 515,
    acceleration: 3.1,
    weight: 1350,
    cylinder: 8,
    torgue: 875,
    img: "2009_Gumpert_Apollo_S.jpg",
  },
  {
    id: 2,
    year: 2012,
    brand: "Gumpert",
    model: "Apollo Enraged",
    topspeed: 330,
    power: 573,
    acceleration: 2.9,
    weight: 1325,
    cylinder: 8,
    torgue: 919,
    img: "2012_Gumpert_Apollo_Enraged.jpg",
  },
];
