export const mitsubishi_models = [
  {
    id: 1,
    year: 1999,
    brand: "Mitsubishi",
    model: "Lancer Evolution VI GSR",
    topspeed: 250,
    power: 209,
    acceleration: 5.0,
    weight: 1280,
    cylinder: 4,
    torgue: 407,
    img: "1999_Mitsubishi_Lancer_Evolution_VI_GSR.jpg",
  },
  {
    id: 2,
    year: 2004,
    brand: "Mitsubishi",
    model: "Lancer Evolution VIII MR",
    topspeed: 255,
    power: 207,
    acceleration: 5.2,
    weight: 1410,
    cylinder: 4,
    torgue: 400,
    img: "2004_Mitsubishi_Lancer_Evolution_VIII_MR.jpg",
  },
  {
    id: 3,
    year: 2008,
    brand: "Mitsubishi",
    model: "Lancer Evolution X GSR",
    topspeed: 250,
    power: 227,
    acceleration: 5.7,
    weight: 1540,
    cylinder: 4,
    torgue: 426,
    img: "2008_Mitsubishi_Lancer_Evolution_X_GSR.jpg",
  },
];
